package social;

import javax.swing.*;
import java.awt.*;


public class SocialGui extends JFrame {

	/*
	 * Default UID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	// The following components are declared public
	// in order to allow testing the user interface
	
	/**
	 * The code of the person to log in
	 */
	public JTextField id ;
	
	/**
	 * The button to perform login
	 */
	public JButton login ;
	
	/**
	 * The label that shall contain the info
	 * of the logged in person 
	 */
	public JLabel name ;
	
	/**
	 * The list of friends of the person
	 * that is logged in
	 */
	public JList<String> friends ;
	

	public SocialGui(Social m){
		setLayout(new BorderLayout());
		setTitle("MyFacebook");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Set the font to Arial
        Font font = new Font("Arial", Font.PLAIN, 12);
        setFont(font);
        
        // Main panel with GridLayout
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout());

        
        


	}


}
